CUDA_VISIBLE_DEVICES=7 python main.py \
 --experiment_description OTDA \
 --run_description UCIHAR \
 --da_method OTDA \
 --dataset UCIHAR \
 --num_runs 5 \
 --lr 0.01 \
 --cls_trade_off 1 \
 --ot_t_trade_off 0.5 \
 --ot_f_trade_off 0.5 \
 --stop_step 600 \
 --test_interval 5 \
 --print_freq 1 \
 --ot_type partial \
 --eta1 0.01 \
 --eta2 0.5 \
 --epsilon 0.5 \
 --tau 0.3 \
 --mass 0.9 \
 --k 1 \
 --topk 1 \
 --freq_aux_trade_off 0.5 \
 --freq_weight_lambda 0 \
 --time_weight_lambda 0 \
 --mix_lambda 1
